# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-13 17:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groggery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='酒店名')),
                ('image', models.ImageField(upload_to='images/groggery', verbose_name='酒店图片')),
            ],
            options={
                'verbose_name': '酒店',
                'verbose_name_plural': '酒店',
                'db_table': 'groggery',
            },
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='行程时间')),
                ('day', models.IntegerField(verbose_name='第几天')),
                ('visit_address', models.CharField(max_length=20, verbose_name='游访地点')),
                ('content', models.TextField(verbose_name='游玩内容')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_groggery', to='info.Groggery', verbose_name='入住酒店')),
            ],
            options={
                'verbose_name': '行程',
                'verbose_name_plural': '行程',
                'db_table': 'journey',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='评论发表时间')),
                ('assist', models.BigIntegerField(verbose_name='赞同数')),
                ('oppose', models.BigIntegerField(verbose_name='反对数')),
            ],
            options={
                'verbose_name': '用户评论',
                'verbose_name_plural': '用户评论',
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='Scenic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='照片名')),
                ('image', models.ImageField(upload_to='images/scenic', verbose_name='景点照片')),
            ],
            options={
                'verbose_name': '相册',
                'verbose_name_plural': '相册',
                'db_table': 'scenic',
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='套餐名')),
                ('nation', models.CharField(max_length=20, verbose_name='国家')),
                ('coordinate', models.CharField(max_length=50, verbose_name='坐标')),
                ('originating', models.CharField(max_length=20, verbose_name='始发地')),
                ('end_locale', models.CharField(max_length=20, verbose_name='结束地')),
                ('through_time', models.IntegerField(verbose_name='历时天数')),
                ('day', models.IntegerField(verbose_name='白天数')),
                ('night', models.IntegerField(verbose_name='晚上数')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(choices=[(1, 'delete'), (0, 'exist')], default=0, verbose_name='被删除')),
                ('favorites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_user', to=settings.AUTH_USER_MODEL, verbose_name='被喜欢')),
                ('groggery', models.ManyToManyField(to='info.Groggery', verbose_name='酒店')),
            ],
            options={
                'verbose_name': '旅游项目',
                'verbose_name_plural': '旅游项目',
                'db_table': 'scheme',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_number', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='分数')),
                ('category', models.IntegerField(choices=[(1, '清洁度'), (2, '服务'), (3, '舒适'), (4, '条件')], default=1, verbose_name='评分类别')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='评分者')),
            ],
            options={
                'verbose_name': '评价',
                'verbose_name_plural': '评价',
                'db_table': 'score',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='出发时间')),
                ('end_date', models.DateField(verbose_name='返程时间')),
                ('surplus', models.IntegerField(verbose_name='剩余票数')),
                ('unit_price', models.IntegerField(verbose_name='当天票价')),
                ('Scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Scheme', verbose_name='套餐对象')),
            ],
            options={
                'verbose_name': '票务',
                'verbose_name_plural': '票务',
                'db_table': 'ticket',
            },
        ),
        migrations.AddField(
            model_name='scheme',
            name='score',
            field=models.ManyToManyField(to='info.Score', verbose_name='评分'),
        ),
        migrations.AddField(
            model_name='review',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_scheme', to='info.Scheme', verbose_name='被评论套餐'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_user', to=settings.AUTH_USER_MODEL, verbose_name='评论者'),
        ),
        migrations.AddField(
            model_name='journey',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Scheme', verbose_name='所属套餐'),
        ),
    ]
