# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-26 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='contains_content',
            field=models.TextField(default='', verbose_name='包含内容'),
        ),
    ]
