# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-11 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='hotel',
            field=models.CharField(max_length=120, null=True, verbose_name='入住酒店'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='visit_address',
            field=models.CharField(max_length=120, verbose_name='游访地点'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='name',
            field=models.CharField(max_length=120, verbose_name='套餐名'),
        ),
    ]
