# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-13 17:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='favorites',
        ),
        migrations.AddField(
            model_name='scheme',
            name='favorites',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='被喜欢'),
        ),
    ]
