# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-27 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_scheme_contains_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='through_time',
        ),
    ]
