# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-15 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20190413_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='nation',
        ),
    ]
