# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-12 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20190711_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='hotel',
            field=models.CharField(max_length=600, null=True, verbose_name='入住酒店'),
        ),
    ]
