# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-27 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_remove_scheme_through_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='酒店名')),
                ('image', models.ImageField(upload_to='images/hotel', verbose_name='酒店图片')),
            ],
            options={
                'verbose_name': '酒店',
                'verbose_name_plural': '酒店',
                'db_table': 'hotel',
            },
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='groggery',
        ),
        migrations.AlterField(
            model_name='journey',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_hotel', to='info.Hotel', verbose_name='入住酒店'),
        ),
        migrations.DeleteModel(
            name='Groggery',
        ),
        migrations.AddField(
            model_name='scheme',
            name='Hotel',
            field=models.ManyToManyField(blank=True, to='info.Hotel', verbose_name='酒店'),
        ),
    ]
