# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-15 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_remove_scheme_nation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='end_locale',
            field=models.CharField(max_length=20, verbose_name='目的地'),
        ),
    ]
