# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-27 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20190427_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheme',
            old_name='Hotel',
            new_name='hotel',
        ),
    ]
