# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-15 19:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20190415_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='被喜欢'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='groggery',
            field=models.ManyToManyField(blank=True, null=True, to='info.Groggery', verbose_name='酒店'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='score',
            field=models.ManyToManyField(blank=True, null=True, to='info.Score', verbose_name='评分'),
        ),
    ]
