# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-21 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20190712_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='scenic',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='scheme',
        ),
        migrations.RemoveField(
            model_name='review',
            name='scheme',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='score',
        ),
        migrations.RemoveField(
            model_name='score',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='scheme',
        ),
        migrations.DeleteModel(
            name='Journey',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Scenic',
        ),
        migrations.DeleteModel(
            name='Scheme',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
