# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-05 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20190428_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='contains_content',
            field=models.TextField(verbose_name='包含内容'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='coordinate',
            field=models.CharField(max_length=50, null=True, verbose_name='坐标'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='feature',
            field=models.TextField(verbose_name='特色'),
        ),
    ]
