# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-06 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20190505_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='scenic',
        ),
        migrations.AddField(
            model_name='journey',
            name='scenic',
            field=models.ManyToManyField(blank=True, to='info.Scenic', verbose_name='相册'),
        ),
    ]
