# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-06 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_auto_20190506_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='scenic',
            field=models.ManyToManyField(blank=True, null=True, to='info.Scenic', verbose_name='相册'),
        ),
    ]
