# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-06 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_auto_20190506_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='hotel',
            field=models.CharField(max_length=300, null=True, verbose_name='入住酒店'),
        ),
    ]
