# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-06 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_auto_20190506_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='visit_address',
            field=models.CharField(max_length=150, verbose_name='游访地点'),
        ),
    ]
