# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-08 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_auto_20190506_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='time',
            field=models.TimeField(null=True, verbose_name='行程时间'),
        ),
    ]
