# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-25 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_auto_20190508_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='scenic',
            field=models.ManyToManyField(blank=True, to='info.Scenic', verbose_name='相册'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_number',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='分数'),
        ),
    ]
