# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-01 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0019_auto_20190628_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenic',
            name='image',
            field=models.ImageField(upload_to='media/images/scenic', verbose_name='景点照片'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_number',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=4, verbose_name='分数'),
        ),
    ]
